# Generated by Django 4.2.18 on 2025-04-26 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obs_system_app', '0002_staffs_date_of_birth_staffs_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='credit_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjects',
            name='has_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subjects',
            name='has_theory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='course_id',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='obs_system_app.courses'),
        ),
    ]
