# Generated by Django 4.2.18 on 2025-04-26 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obs_system_app', '0003_subjects_credit_hours_subjects_has_lab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='subject_type',
            field=models.CharField(choices=[('Compulsory', 'Compulsory'), ('Elective', 'Elective')], default='Compulsory', max_length=20),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='obs_system_app.courses'),
        ),
    ]
