# Generated by Django 4.2.18 on 2025-04-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_system_app', '0004_subjects_subject_type_alter_subjects_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_code_dep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
