# Generated by Django 4.2.18 on 2025-05-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_system_app', '0005_subjects_semester_subjects_subject_code_dep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
