# Generated by Django 4.2.18 on 2025-05-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_system_app', '0006_alter_courses_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='academic_title',
            field=models.CharField(blank=True, choices=[('Prof. Dr.', 'Prof. Dr.'), ('Doç. Dr.', 'Doç. Dr.'), ('Dr. Öğr. Üyesi', 'Dr. Öğr. Üyesi'), ('Arş. Gör.', 'Arş. Gör.'), ('', 'None')], default='', max_length=50),
        ),
    ]
