# Generated by Django 4.2.18 on 2025-05-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obs_system_app', '0007_staffs_academic_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='academic_title',
        ),
    ]
