# Generated by Django 4.2.18 on 2025-05-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_system_app', '0008_remove_staffs_academic_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='students',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='credit_hours',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='has_lab',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='has_theory',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='subject_code',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='subject_code_dep',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='subject_description',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='subject_type',
        ),
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
