# Generated by Django 4.2.18 on 2025-05-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_system_app', '0009_remove_staffs_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='credit_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjects',
            name='has_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subjects',
            name='has_theory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subjects',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_code_dep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_type',
            field=models.CharField(choices=[('Compulsory', 'Compulsory'), ('Elective', 'Elective')], default='Compulsory', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
