# Generated by Django 4.2.18 on 2025-05-10 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obs_system_app', '0010_subjects_credit_hours_subjects_has_lab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obs_system_app.staffs'),
        ),
        migrations.CreateModel(
            name='StudentSubjectSelection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs_system_app.students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs_system_app.subjects')),
            ],
        ),
    ]
