# Generated by Django 4.2.18 on 2025-05-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_system_app', '0011_students_advisor_studentsubjectselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='ects_credits',
            field=models.FloatField(default=0.0),
        ),
    ]
