# Generated by Django 4.2.18 on 2025-05-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_system_app', '0012_subjects_ects_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='expected_graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
