# Generated by Django 4.2.18 on 2025-05-10 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obs_system_app', '0014_gradecomponent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='subject_assignment_marks',
            new_name='final_grade',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='subject_exam_marks',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='grade_letter',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='StudentComponentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs_system_app.gradecomponent')),
                ('student_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs_system_app.studentresult')),
            ],
        ),
    ]
