# Generated by Django 4.2.18 on 2025-05-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_system_app', '0015_rename_subject_assignment_marks_studentresult_final_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='current_semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='students',
            name='current_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
