# Generated by Django 4.2.18 on 2025-05-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obs_system_app', '0016_students_current_semester_students_current_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 'Fall'), (2, 'Spring')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('session_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs_system_app.sessionyearmodel')),
            ],
        ),
    ]
